name: 'ivliab/serverless-deploy'
description: 'Deploy Serverless python 3.8'
inputs:
  stage:
    description: 'the stage to deploy'
    required: true
  region:
    description: 'the region to deploy'
    required: true
  workdir:
    description: 'the serverless workdir'
    required: true
runs:
  using: 'docker'
  image: 'docker://ivliab/serverless-python-38:latest'
  args:
    - ${{ inputs.stage }}
    - ${{ inputs.region }}
    - ${{ inputs.workdir }}
